# Configuration for actions/labeler
# Automatically labels PRs based on file paths changed

# Core code changes
'core':
  - changed-files:
    - any-glob-to-any-file: 'pkg/**/*'

# Authentication & JWT
'auth':
  - changed-files:
    - any-glob-to-any-file: 'pkg/auth/**/*'

# Phoenix Channels
'channels':
  - changed-files:
    - any-glob-to-any-file: 'pkg/channels/**/*'

# Configuration
'config':
  - changed-files:
    - any-glob-to-any-file: 'pkg/config/**/*'

# Proxy engine
'proxy':
  - changed-files:
    - any-glob-to-any-file: 'pkg/proxy/**/*'

# CLI changes
'cli':
  - changed-files:
    - any-glob-to-any-file: 'cmd/**/*'

# Documentation
'documentation':
  - changed-files:
    - any-glob-to-any-file:
      - '*.md'
      - 'docs/**/*'
      - '.github/**/*.md'

# Tests
'testing':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*_test.go'
      - 'test_server/**/*'

# CI/CD
'ci/cd':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/dependabot.yml'
      - '.golangci.yml'

# Docker
'docker':
  - changed-files:
    - any-glob-to-any-file:
      - 'Dockerfile*'
      - '.dockerignore'
      - 'docker-compose*.yml'

# Dependencies
'dependencies':
  - changed-files:
    - any-glob-to-any-file:
      - 'go.mod'
      - 'go.sum'

# Build system
'build':
  - changed-files:
    - any-glob-to-any-file:
      - 'Makefile'
      - 'build/**/*'

# Configuration files
'config-files':
  - changed-files:
    - any-glob-to-any-file:
      - '*.yml'
      - '*.yaml'
      - '*.toml'
      - '*.json'
      - '.env*'

# Database/Storage
'storage':
  - changed-files:
    - any-glob-to-any-file: 'pkg/**/storage*.go'
