# golangci-lint v2 configuration for Telephone
# https://golangci-lint.run/docs/configuration/file/

version: "2"

run:
  tests: true
  build-tags: []
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: true
      print-linter-name: true

linters:
  default: none
  enable:
    - errcheck # Checks for unchecked errors
    - govet # Reports suspicious constructs
    - ineffassign # Detects ineffectual assignments
    - staticcheck # Go static analysis (includes gosimple and stylecheck)
    - unused # Checks for unused constants, variables, functions and types
    - misspell # Finds commonly misspelled English words
    - revive # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - gosec # Inspects source code for security problems
    - unconvert # Removes unnecessary type conversions
    - goconst # Finds repeated strings that could be replaced by a constant
    - bodyclose # Checks whether HTTP response body is closed successfully
    - errname # Checks that sentinel errors are prefixed with Err
    - errorlint # Find code that will cause problems with the error wrapping scheme
    - exhaustive # Check exhaustiveness of enum switch statements
    - copyloopvar # Checks for pointers to enclosing loop variables
    - gochecknoinits # Checks that no init functions are present
    - gocritic # Provides diagnostics that check for bugs, performance and style issues
    - gocyclo # Computes and checks the cyclomatic complexity of functions
    - godot # Check if comments end in a period
    - goprintffuncname # Checks that printf-like functions are named with f at the end
    - nilerr # Finds the code that returns nil even if it checks that the error is not nil
    - nolintlint # Reports ill-formed or insufficient nolint directives
    - prealloc # Finds slice declarations that could potentially be pre-allocated
    - predeclared # Finds code that shadows one of Go's predeclared identifiers
    - thelper # Detects golang test helpers without t.Helper() call
    - unparam # Reports unused function parameters
    - whitespace # Tool for detection of leading and trailing whitespace
    - wsl_v5 # Whitespace Linter (v5 for golangci-lint v2)

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*database/sql.Rows).Close
        - (*database/sql.DB).Close

    govet:
      enable-all: true
      disable:
        - fieldalignment # Too strict for most use cases

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - unnamedResult

    gocyclo:
      min-complexity: 15

    godot:
      scope: declarations
      capital: false

    misspell:
      locale: US

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id

    gosec:
      excludes:
        - G404 # Allow weak random number generator in non-crypto contexts
      config:
        global:
          nosec: false
          show-ignored: true

    staticcheck:
      checks: ["all"]

    whitespace:
      multi-if: false
      multi-func: false

    wsl_v5:
      # Reduce strictness - allow first statement in block without blank line
      allow-first-in-block: true

  exclusions:
    presets: []
    paths:
      - bin
      - vendor
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - goconst
          - gochecknoinits

      # Ignore long lines in tests with URLs or long strings
      - source: "https?://"
        linters:
          - lll

formatters:
  enable:
    - gofmt # Checks whether code was gofmt-ed
    - goimports # Checks import statements are formatted

  settings:
    gofmt:
      simplify: true

    goimports:
      local-prefixes:
        - github.com/verastack/telephone

severity:
  default: error
  rules:
    - linters:
        - revive
      severity: warning
